[package]
name = "steeldb"
version = "0.1.1"
edition = "2021"
description = "A simple database built from scratch in Rust"
license = "Apache-2.0"

[dependencies]
lalrpop-util = { version = "0.20.0", features = ["lexer", "unicode"] }
steeldb-parser = { path = "steeldb-parser", version = "0.1.1" }
