[package]
name = "steeldb"
version = "0.1.0"
edition = "2021"

[dependencies]
lalrpop-util = { version = "0.20.0", features = ["lexer", "unicode"] }
steeldb-parser = { path = "steeldb-parser", version = "0.1.0" }
